In [31]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [32]:
#import tensorflow as tf
import pandas as pd
import sklearn
import numpy as np

In [33]:
data = pd.read_csv('/content/drive/MyDrive/웹개발/vegita/data/price data.csv',sep=',')
data

year  avgTemp  minTemp  maxTemp  rainFall  avgPrice
0     20100101     -4.9    -11.0      0.9       0.0      2123
1     20100102     -3.1     -5.5      5.5       0.8      2123
2     20100103     -2.9     -6.9      1.4       0.0      2123
3     20100104     -1.8     -5.1      2.2       5.9      2020
4     20100105     -5.2     -8.7     -1.8       0.7      2060
...        ...      ...      ...      ...       ...       ...
2917  20171227     -3.9     -8.0      0.7       0.0      2865
2918  20171228     -1.5     -6.9      3.7       0.0      2884
2919  20171229      2.9     -2.1      8.0       0.0      2901
2920  20171230      2.9     -1.6      7.1       0.6      2901
2921  20171231      2.1     -2.0      5.8       0.4      2901

[2922 rows x 6 columns]

In [34]:
xy = np.array(data, dtype=np.float32)
xy

array([[ 2.0100100e+07, -4.9000001e+00, -1.1000000e+01,  8.9999998e-01,
         0.0000000e+00,  2.1230000e+03],
       [ 2.0100102e+07, -3.0999999e+00, -5.5000000e+00,  5.5000000e+00,
         8.0000001e-01,  2.1230000e+03],
       [ 2.0100104e+07, -2.9000001e+00, -6.9000001e+00,  1.4000000e+00,
         0.0000000e+00,  2.1230000e+03],
       ...,
       [ 2.0171228e+07,  2.9000001e+00, -2.0999999e+00,  8.0000000e+00,
         0.0000000e+00,  2.9010000e+03],
       [ 2.0171230e+07,  2.9000001e+00, -1.6000000e+00,  7.0999999e+00,
         6.0000002e-01,  2.9010000e+03],
       [ 2.0171232e+07,  2.0999999e+00, -2.0000000e+00,  5.8000002e+00,
         4.0000001e-01,  2.9010000e+03]], dtype=float32)

In [35]:
x_data = xy[:, 1:-1]
x_data

array([[ -4.9, -11. ,   0.9,   0. ],
       [ -3.1,  -5.5,   5.5,   0.8],
       [ -2.9,  -6.9,   1.4,   0. ],
       ...,
       [  2.9,  -2.1,   8. ,   0. ],
       [  2.9,  -1.6,   7.1,   0.6],
       [  2.1,  -2. ,   5.8,   0.4]], dtype=float32)

괄호 빼먹지 말기!!

In [36]:
y_data = xy[:,[-1]]
y_data

array([[2123.],
       [2123.],
       [2123.],
       ...,
       [2901.],
       [2901.],
       [2901.]], dtype=float32)

In [37]:
X = tf.placeholder(tf.float32, shape=(None,4))
Y = tf.placeholder(tf.float32, shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [38]:
hypothesis = tf.matmul(X,W) + b

In [39]:
cost = tf.reduce_mean(tf.square(hypothesis-Y))

In [40]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.000005)

In [41]:
train = optimizer.minimize(cost)

In [42]:
sess = tf.Session()

In [43]:
sess.run(tf.global_variables_initializer())

In [44]:
for step in range(100001):
    cost_, hypo_, _ = sess.run([cost, hypothesis, train], feed_dict={X:x_data, Y:y_data})
    if step%500 == 0:
        print("#",step,"cost: ",cost)
        print("-배추가격: ",hypo_[0])

# 0 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [14.574978]
# 500 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [-265.73843]
# 1000 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [42.728714]
# 1500 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [323.8627]
# 2000 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [573.6837]
# 2500 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [795.6665]
# 3000 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [992.95966]
# 3500 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [1168.3444]
# 4000 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [1324.2782]
# 4500 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [1462.9344]
# 5000 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [1586.242]
# 5500 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [1695.9064]
# 6000 cost:  Tensor("Mean_2:0", shape=(), dtype=float32)
-배추가격:  [1793

In [45]:
saver = tf.train.Saver()
save_path = saver.save(sess, '/content/drive/MyDrive/웹개발/vegita/saved.cpkt')
print("학습된 모델을 저장")

학습된 모델을 저장
